### PR TITLE
Codereview/Kumar

### PR DESCRIPTION
**Pull request by kummy98**
## Premise

Hi, for the app of group1 which is find my phone i did the encryption and of course decryption of all the message sended and received by the app.
I used a XOR encryption which is a symmetric encryption so: base_text ^ key = encrypted_text and encrypted_text^key=base_text.
I used this kind of encryption because it doesn't give problems with the length of the encrypted_text.
The password used for encryption/decryption it's saved using sharedPreferances using the passwordManager class.
The randomStrinGeneratorUtils class was created to help in the testing of the main class.

## Changes

-Added the interface of the cipher class.
-Added the class to cipher all the message.
-Added a passwordManager to store the password used for encryption.
-Added a class to generate random strings with random length for testing.

### Footer

I also implemented the encryption in the app but i prefer not to put in this pr because it's a bit messy.

### CODE REVIEW

**Comment by RicDeZen** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/main/java/ingsw/group1/findmyphone/cryptography/RandomStringGeneratorUtils.java  2
- app/src/main/java/ingsw/group1/findmyphone/cryptography/PasswordManager.java  1
- app/src/main/java/ingsw/group1/findmyphone/cryptography/SMSCipher.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/RicDeZen/ingsw-group1-findmyphone/pullRequest?prid=5095228&bid=16759827)

**Comment by RicDeZen** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/main/java/ingsw/group1/findmyphone/cryptography/RandomStringGeneratorUtils.java  2
- app/src/main/java/ingsw/group1/findmyphone/cryptography/PasswordManager.java  1
- app/src/main/java/ingsw/group1/findmyphone/cryptography/SMSCipher.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/RicDeZen/ingsw-group1-findmyphone/pullRequest?prid=5095228&bid=16759827)

**Comment by RicDeZen** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/main/java/ingsw/group1/findmyphone/cryptography/RandomStringGeneratorUtils.java  2
- app/src/main/java/ingsw/group1/findmyphone/cryptography/PasswordManager.java  1
- app/src/main/java/ingsw/group1/findmyphone/cryptography/SMSCipher.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/RicDeZen/ingsw-group1-findmyphone/pullRequest?prid=5095228&bid=16759827)

**Comment by RicDeZen** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/main/java/ingsw/group1/findmyphone/cryptography/RandomStringGeneratorUtils.java  2
- app/src/main/java/ingsw/group1/findmyphone/cryptography/PasswordManager.java  1
- app/src/main/java/ingsw/group1/findmyphone/cryptography/SMSCipher.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/RicDeZen/ingsw-group1-findmyphone/pullRequest?prid=5095228&bid=16759827)

**Review by EdoardoRaimondi — CHANGES_REQUESTED** [review]
The code is orderly. The usage of xor method without any restriction of key length is quite vulnerable (such as all ECB encryptions) but for your data it should be enough (as long as you know, it's your choice).

-`MessageCipher `interface : I would have spent some lines of comments, even if names are self descriptive. I know I can find them in the MessageCipher class but the interfaces should appear independent from the classes that implement them.

-Happy to see you created your own `RandomGeneratorStringUtils`, and you do it well! 👍  But, why didn't you use the java class `RandomStringUtils`? 

-`SMSCipher` class:
Are methods such as : encrypt, decrypt, addPadding, fromStringToAscii supposed to be called outside this class? 
Yes -> probably it should be better create apposite classes for them
No -> why aren't they private?

Add some descriptive comments inside methods like `encrypt`, `decrypt`, sometimes it's hard to understand what's going on
 
**-lines 63, 64, 83** : It's isn't necessary to call SMSChiper on the method

**CONCLUSION**
You do it rigth. Except some inaccuracy your code is clean. My compliments, it's always tricky working with encryption and decryption. Keep this proactive attitude!

**Comment by ricdezen** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/main/java/ingsw/group1/findmyphone/cryptography/SMSCipher.java  3
- app/src/main/java/ingsw/group1/findmyphone/cryptography/RandomStringGeneratorUtils.java  2
- app/src/main/java/ingsw/group1/findmyphone/cryptography/SMSCipherUtils.java  2
- app/src/main/java/ingsw/group1/findmyphone/cryptography/PasswordManager.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/RicDeZen/ingsw-group1-findmyphone/pullRequest?prid=5095228&bid=16759827)

**Comment by kummy98** [comment]
First of all thanks for the review,
-As you suggested i added the specs for the interface which were missing.
-I didn't use the RandomStringUtils because characters are chosen from the set of characters whose ASCII value is between 32 and 126 (inclusive) so some characters were missing.
-I Added a SMSCiperUtils for addPadding and fromStringToAscii.
-I left decrypt and encrypt public because in case you want to encrypt with a password and decrypt with another i prefer 2 static method,i'm not sure if this is the best way, also for testing i left them public.
-I added comments as u suggested because they were quite hard to understand.

**Review by EdoardoRaimondi — APPROVED** [review]
That's right.
Anyway I see you don't want to change some methods to private for testing. Just add in the @Before section of the test class this : 

methodName = className.class.getDeclaredMethod("methodName", anyArgumentsRequeried.class);
        methodName.setAccessible(true);

and you can test private methods

**Comment by kummy98** [comment]
I didn't know that , that's very useful, thanks!

**Pull request merged**
