### PR TITLE
SMSLogEvent doesn't need contact name

### PR DESCRIPTION
**Pull request by ricdezen**
## Premise

This pull request will not be up to date after merging Giorgia's contacts update due to a call to the `SMSContactManager` constructor. [Review that first](https://github.com/RicDeZen/ingsw-group1-findmyphone/pull/32) so I can pull and fix this one.

## Changes

- `SMSLogEvent` does not hold the Contact's name anymore, because this would give an incoherence of data when changing the name of a contact.
- `LogItemFormatter` opens the contact manager and searches for contacts matching the address.

## Side Changes

- Removed the old library submodule.
- Tests sometimes load contacts into the database to facilitate log testing, they empty it afterwards.

### Footer

[Woof](https://www.google.com/search?q=corgi&source=lnms&tbm=isch)

### CODE REVIEW

**Comment by RicDeZen** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/test/java/ingsw/group1/findmyphone/RandomSMSLogEventGeneratorTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/RicDeZen/ingsw-group1-findmyphone/pullRequest?prid=5067838&bid=16674597)

**Comment by ricdezen** [comment]
Ignore the Android CI checks, this is probably a leftover from when I was trying to fix it. Will probably not be added to the development branch.

**Comment by ricdezen** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/test/java/ingsw/group1/findmyphone/RandomSMSLogEventGeneratorTest.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/RicDeZen/ingsw-group1-findmyphone/pullRequest?prid=5067838&bid=16674597)

**Comment by turcato-niccolo** [comment]
> * `SMSLogEvent` does not hold the Contact's name anymore, because this would give an incoherence of data when changing the name of a contact.

I don't quite understand, wouldn't it update the name when the log is re-created?

**Comment by ricdezen** [comment]
Now it does, earlier it was stored in the event itself

**Comment by ricdezen** [comment]
I am including this in the next pull.

**Pull request closed without merging**
